linters-settings:
  dupl:
    threshold: 100
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  funlen:
    lines: 65
    statements: 40
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
      - whyNoLint
  gofumpt:
    extra-rules: true
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
  govet:
    check-shadowing: false
  misspell:
    locale: US
  nestif:
    min-complexity: 4
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
  # - dupl - it's very slow, enable if you really know why you need it
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - megacheck # (staticcheck + gosimple + unused in one linter)
    - revive
    - typecheck
    - unused # will be used insted of varcheck + deadcode + structcheck. More info https://github.com/golangci/golangci-lint/issues/1841

issues:
  exclude-rules:
    - path: integration-test
      linters:
        - paralleltest
        - godot
    - path: internal/controller/http
      linters:
        - godot
  exclude:
    - exported func .* returns unexported type .*, which can be annoying to use

run:
  skip-dirs:
    - docs
  skip-files:
    - ".*_test\\.go"
