version: "2"
services:
  postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - ./.artifacts/pg-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust" # ONLY FOR TESTING
  app:
    restart: always
    build:
      dockerfile: build/Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - "./scripts/wait_for_it.sh:/app/wait_for_it.sh"
    depends_on:
      - postgres
    command: ["sh", "./wait_for_it.sh", "--", "./placeapi"]